apiVersion: v1
kind: Service
metadata:
  labels:
    app: adservice
  name: adservice
  namespace: prod
spec:
  ports:
  - name: grpc
    port: 9555
    targetPort: grpc
  selector:
    app: adservice
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: cartservice
  name: cartservice
  namespace: prod
spec:
  ports:
  - name: grpc
    port: 7070
    targetPort: grpc
  selector:
    app: cartservice
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: checkoutservice
  name: checkoutservice
  namespace: prod
spec:
  ports:
  - name: grpc
    port: 5050
    targetPort: grpc
  selector:
    app: checkoutservice
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: currencyservice
  name: currencyservice
  namespace: prod
spec:
  ports:
  - name: grpc
    port: 7000
    targetPort: grpc
  selector:
    app: currencyservice
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: emailservice
  name: emailservice
  namespace: prod
spec:
  ports:
  - name: grpc
    port: 8080
    targetPort: grpc
  selector:
    app: emailservice
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: frontend
  name: frontend
  namespace: prod
spec:
  ports:
  - name: http
    port: 8080
    targetPort: http
  selector:
    app: frontend
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: paymentservice
  name: paymentservice
  namespace: prod
spec:
  ports:
  - name: grpc
    port: 50051
    targetPort: grpc
  selector:
    app: paymentservice
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: productcatalogservice
  name: productcatalogservice
  namespace: prod
spec:
  ports:
  - name: grpc
    port: 3550
    targetPort: grpc
  selector:
    app: productcatalogservice
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: recommendationservice
  name: recommendationservice
  namespace: prod
spec:
  ports:
  - name: grpc
    port: 8080
    targetPort: grpc
  selector:
    app: recommendationservice
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: shippingservice
  name: shippingservice
  namespace: prod
spec:
  ports:
  - name: grpc
    port: 50051
    targetPort: grpc
  selector:
    app: shippingservice
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: adservice
  name: adservice
  namespace: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adservice
  template:
    metadata:
      labels:
        app: adservice
    spec:
      containers:
      - env:
        - name: PORT
          value: "9555"
        image: athena-registry:5000/athena-adservice:9034b09
        imagePullPolicy: IfNotPresent
        livenessProbe:
          grpc:
            port: 9555
          initialDelaySeconds: 10
          periodSeconds: 10
        name: adservice
        ports:
        - containerPort: 9555
          name: grpc
        readinessProbe:
          grpc:
            port: 9555
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          limits:
            cpu: 300m
            memory: 384Mi
          requests:
            cpu: 100m
            memory: 256Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
          runAsNonRoot: true
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cartservice
  name: cartservice
  namespace: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cartservice
  template:
    metadata:
      labels:
        app: cartservice
    spec:
      containers:
      - env:
        - name: REDIS_ADDR
          value: redis-cart:6379
        image: athena-registry:5000/athena-cartservice:9034b09
        imagePullPolicy: IfNotPresent
        livenessProbe:
          grpc:
            port: 7070
          initialDelaySeconds: 10
          periodSeconds: 10
        name: cartservice
        ports:
        - containerPort: 7070
          name: grpc
        readinessProbe:
          grpc:
            port: 7070
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          limits:
            cpu: 200m
            memory: 192Mi
          requests:
            cpu: 50m
            memory: 96Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
          runAsNonRoot: true
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: checkoutservice
  name: checkoutservice
  namespace: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: checkoutservice
  template:
    metadata:
      labels:
        app: checkoutservice
    spec:
      containers:
      - env:
        - name: CART_SERVICE_ADDR
          value: cartservice:7070
        - name: CURRENCY_SERVICE_ADDR
          value: currencyservice:7000
        - name: EMAIL_SERVICE_ADDR
          value: emailservice:8080
        - name: PAYMENT_SERVICE_ADDR
          value: paymentservice:50051
        - name: PORT
          value: "5050"
        - name: PRODUCT_CATALOG_SERVICE_ADDR
          value: productcatalogservice:3550
        - name: SHIPPING_SERVICE_ADDR
          value: shippingservice:50051
        image: athena-registry:5000/athena-checkoutservice:9034b09
        imagePullPolicy: IfNotPresent
        livenessProbe:
          grpc:
            port: 5050
          initialDelaySeconds: 10
          periodSeconds: 10
        name: checkoutservice
        ports:
        - containerPort: 5050
          name: grpc
        readinessProbe:
          grpc:
            port: 5050
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          limits:
            cpu: 200m
            memory: 128Mi
          requests:
            cpu: 50m
            memory: 64Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
          runAsNonRoot: true
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: currencyservice
  name: currencyservice
  namespace: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: currencyservice
  template:
    metadata:
      labels:
        app: currencyservice
    spec:
      containers:
      - env:
        - name: DISABLE_PROFILER
          value: "1"
        - name: PORT
          value: "7000"
        image: athena-registry:5000/athena-currencyservice:9034b09
        imagePullPolicy: IfNotPresent
        livenessProbe:
          grpc:
            port: 7000
          initialDelaySeconds: 10
          periodSeconds: 10
        name: currencyservice
        ports:
        - containerPort: 7000
          name: grpc
        readinessProbe:
          grpc:
            port: 7000
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          limits:
            cpu: 200m
            memory: 128Mi
          requests:
            cpu: 50m
            memory: 64Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
          runAsNonRoot: true
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: emailservice
  name: emailservice
  namespace: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: emailservice
  template:
    metadata:
      labels:
        app: emailservice
    spec:
      containers:
      - env:
        - name: DISABLE_PROFILER
          value: "1"
        - name: PORT
          value: "8080"
        image: athena-registry:5000/athena-emailservice:9034b09
        imagePullPolicy: IfNotPresent
        livenessProbe:
          grpc:
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
        name: emailservice
        ports:
        - containerPort: 8080
          name: grpc
        readinessProbe:
          grpc:
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          limits:
            cpu: 200m
            memory: 192Mi
          requests:
            cpu: 50m
            memory: 96Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
          runAsNonRoot: true
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: frontend
  name: frontend
  namespace: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - env:
        - name: PORT
          value: "8080"
        - name: AD_SERVICE_ADDR
          value: adservice:9555
        - name: CART_SERVICE_ADDR
          value: cartservice:7070
        - name: CHECKOUT_SERVICE_ADDR
          value: checkoutservice:5050
        - name: CURRENCY_SERVICE_ADDR
          value: currencyservice:7000
        - name: PRODUCT_CATALOG_SERVICE_ADDR
          value: productcatalogservice:3550
        - name: RECOMMENDATION_SERVICE_ADDR
          value: recommendationservice:8080
        - name: SHIPPING_SERVICE_ADDR
          value: shippingservice:50051
        - name: SHOPPING_ASSISTANT_SERVICE_ADDR
          value: shoppingassistantservice.excluded.invalid:9000
        image: athena-registry:5000/athena-frontend:9034b09
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /_healthz
            port: http
          initialDelaySeconds: 10
          periodSeconds: 10
        name: frontend
        ports:
        - containerPort: 8080
          name: http
        readinessProbe:
          httpGet:
            path: /_healthz
            port: http
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          limits:
            cpu: 250m
            memory: 128Mi
          requests:
            cpu: 50m
            memory: 64Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
          runAsNonRoot: true
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: paymentservice
  name: paymentservice
  namespace: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: paymentservice
  template:
    metadata:
      labels:
        app: paymentservice
    spec:
      containers:
      - env:
        - name: DISABLE_PROFILER
          value: "1"
        - name: PORT
          value: "50051"
        image: athena-registry:5000/athena-paymentservice:9034b09
        imagePullPolicy: IfNotPresent
        livenessProbe:
          grpc:
            port: 50051
          initialDelaySeconds: 10
          periodSeconds: 10
        name: paymentservice
        ports:
        - containerPort: 50051
          name: grpc
        readinessProbe:
          grpc:
            port: 50051
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          limits:
            cpu: 200m
            memory: 128Mi
          requests:
            cpu: 50m
            memory: 64Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
          runAsNonRoot: true
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: productcatalogservice
  name: productcatalogservice
  namespace: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: productcatalogservice
  template:
    metadata:
      labels:
        app: productcatalogservice
    spec:
      containers:
      - env:
        - name: PORT
          value: "3550"
        image: athena-registry:5000/athena-productcatalogservice:9034b09
        imagePullPolicy: IfNotPresent
        livenessProbe:
          grpc:
            port: 3550
          initialDelaySeconds: 10
          periodSeconds: 10
        name: productcatalogservice
        ports:
        - containerPort: 3550
          name: grpc
        readinessProbe:
          grpc:
            port: 3550
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          limits:
            cpu: 200m
            memory: 128Mi
          requests:
            cpu: 50m
            memory: 64Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
          runAsNonRoot: true
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: recommendationservice
  name: recommendationservice
  namespace: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: recommendationservice
  template:
    metadata:
      labels:
        app: recommendationservice
    spec:
      containers:
      - env:
        - name: DISABLE_PROFILER
          value: "1"
        - name: PORT
          value: "8080"
        - name: PRODUCT_CATALOG_SERVICE_ADDR
          value: productcatalogservice:3550
        image: athena-registry:5000/athena-recommendationservice:9034b09
        imagePullPolicy: IfNotPresent
        livenessProbe:
          grpc:
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
        name: recommendationservice
        ports:
        - containerPort: 8080
          name: grpc
        readinessProbe:
          grpc:
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          limits:
            cpu: 250m
            memory: 256Mi
          requests:
            cpu: 50m
            memory: 128Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
          runAsNonRoot: true
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: shippingservice
  name: shippingservice
  namespace: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shippingservice
  template:
    metadata:
      labels:
        app: shippingservice
    spec:
      containers:
      - env:
        - name: DISABLE_PROFILER
          value: "1"
        - name: PORT
          value: "50051"
        image: athena-registry:5000/athena-shippingservice:9034b09
        imagePullPolicy: IfNotPresent
        livenessProbe:
          grpc:
            port: 50051
          initialDelaySeconds: 10
          periodSeconds: 10
        name: shippingservice
        ports:
        - containerPort: 50051
          name: grpc
        readinessProbe:
          grpc:
            port: 50051
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          limits:
            cpu: 200m
            memory: 128Mi
          requests:
            cpu: 50m
            memory: 64Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
          runAsNonRoot: true
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: shop
  namespace: prod
spec:
  hostnames:
  - shop-prod.athena.net
  parentRefs:
  - name: athena
    namespace: gateway
  rules:
  - backendRefs:
    - group: ""
      kind: Service
      name: frontend
      port: 8080
    matches:
    - path:
        type: PathPrefix
        value: /
