apiVersion: v1
kind: Service
metadata:
  labels:
    app: media
  name: media
  namespace: dev
spec:
  ports:
  - name: http
    port: 8080
    targetPort: http
  selector:
    app: media
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: media
  name: media
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: media
  template:
    metadata:
      labels:
        app: media
    spec:
      containers:
      - env:
        - name: MEDIA_HTTP_PORT
          value: "8080"
        - name: MEDIA_ENVIRONMENT
          value: dev
        image: athena-registry:5000/athena-media:1492910
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /healthz
            port: http
          initialDelaySeconds: 5
          periodSeconds: 10
        name: media
        ports:
        - containerPort: 8080
          name: http
        readinessProbe:
          httpGet:
            path: /healthz
            port: http
          initialDelaySeconds: 3
          periodSeconds: 5
        resources:
          limits:
            cpu: 250m
            memory: 128Mi
          requests:
            cpu: 50m
            memory: 64Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
          runAsNonRoot: true
      securityContext:
        runAsNonRoot: true
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: media
  namespace: dev
spec:
  hostnames:
  - media-dev.athena.net
  parentRefs:
  - name: athena
    namespace: gateway
  rules:
  - backendRefs:
    - group: ""
      kind: Service
      name: media
      port: 8080
    matches:
    - path:
        type: PathPrefix
        value: /
